diff -Naur ubuntu-sso-client-4.0.0.orig/ubuntu_sso/networkstate/linux.py ubuntu-sso-client-4.0.0/ubuntu_sso/networkstate/linux.py
--- ubuntu-sso-client-4.0.0.orig/ubuntu_sso/networkstate/linux.py	2012-06-27 16:51:18.000000000 +0200
+++ ubuntu-sso-client-4.0.0/ubuntu_sso/networkstate/linux.py	2012-11-26 20:55:19.871804086 +0100
@@ -45,7 +45,6 @@
 
 NM_DBUS_INTERFACE = "org.freedesktop.NetworkManager"
 NM_DBUS_OBJECTPATH = "/org/freedesktop/NetworkManager"
-DBUS_UNKNOWN_SERVICE = "org.freedesktop.DBus.Error.ServiceUnknown"
 
 
 class NetworkManagerState(object):
@@ -72,8 +71,7 @@
 
     def got_error(self, error):
         """Called by DBus when the state is retrieved from NM."""
-        if isinstance(error, self.dbus.exceptions.DBusException) and \
-                error.get_dbus_name() == DBUS_UNKNOWN_SERVICE:
+        if isinstance(error, self.dbus.exceptions.DBusException):
             logger.debug("Network Manager not present")
             # Assuming since Network Manager is not installed,
             # the user has connected in some other way
